# Generated by Django 2.0.5 on 2018-05-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
